services:
  be-suwit-postgres:
    container_name: be-suwit-postgres
    image: postgres:16-alpine
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT:-5432}
    networks:
      - be-suwit-network

networks:
  be-suwit-network:
    name: be-suwit-network
    driver: bridge
    external: true